### ISSUE TITLE
Attacking on Enemy Guidance Dot is behind the Piece

### ISSUE THREAD

**Issue by abdullahqasim01** [dancamma/react-chess-tools#6]
![image](https://github.com/dancamma/react-chess-tools/assets/127170762/77038c63-a4e9-47b9-a273-cd9e1ef814a4)

In this image, the black pawn is about to attack white pawn. The circle or dot use for guiding user about legal moves is behind the white pawn and cannot be seen. Can you fix this?

**Comment by dancamma** [comment]
Hi @abdullahqasim01, thanks for reporting the issue! I've added highlighting of captures similar to react-chessboard. Please let me know if it's okay.
